// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/analyse-tabs/Chips.tsx": () => import("../components/mockups/analyse-tabs/Chips.tsx"),
  "./components/mockups/analyse-tabs/Segmented.tsx": () => import("../components/mockups/analyse-tabs/Segmented.tsx"),
  "./components/mockups/analyse-tabs/StravaTabs.tsx": () => import("../components/mockups/analyse-tabs/StravaTabs.tsx"),
  "./components/mockups/plan-pagina/CoachVerhaal.tsx": () => import("../components/mockups/plan-pagina/CoachVerhaal.tsx"),
  "./components/mockups/plan-pagina/Cockpit.tsx": () => import("../components/mockups/plan-pagina/Cockpit.tsx"),
  "./components/mockups/plan-pagina/PeriodiseringEerst.tsx": () => import("../components/mockups/plan-pagina/PeriodiseringEerst.tsx"),
  "./components/mockups/route-kleuren/Aurora.tsx": () => import("../components/mockups/route-kleuren/Aurora.tsx"),
  "./components/mockups/route-kleuren/DataKrachtig.tsx": () => import("../components/mockups/route-kleuren/DataKrachtig.tsx"),
  "./components/mockups/route-kleuren/HollandsOranje.tsx": () => import("../components/mockups/route-kleuren/HollandsOranje.tsx"),
  "./components/mockups/route-kleuren/HoogContrast.tsx": () => import("../components/mockups/route-kleuren/HoogContrast.tsx"),
  "./components/mockups/route-kleuren/Huidig.tsx": () => import("../components/mockups/route-kleuren/Huidig.tsx"),
  "./components/mockups/route-kleuren/Kompas.tsx": () => import("../components/mockups/route-kleuren/Kompas.tsx"),
  "./components/mockups/route-kleuren/NeonNacht.tsx": () => import("../components/mockups/route-kleuren/NeonNacht.tsx"),
  "./components/mockups/route-kleuren/RetroKoers.tsx": () => import("../components/mockups/route-kleuren/RetroKoers.tsx"),
  "./components/mockups/route-kleuren/Signaal.tsx": () => import("../components/mockups/route-kleuren/Signaal.tsx"),
  "./components/mockups/route-kleuren/SportiefLicht.tsx": () => import("../components/mockups/route-kleuren/SportiefLicht.tsx"),
  "./components/mockups/route-kleuren/Terra.tsx": () => import("../components/mockups/route-kleuren/Terra.tsx"),
  "./components/mockups/sparki-reboot/Prototype.tsx": () => import("../components/mockups/sparki-reboot/Prototype.tsx"),
  "./components/mockups/vandaag-sfeer/Current.tsx": () => import("../components/mockups/vandaag-sfeer/Current.tsx"),
  "./components/mockups/vandaag-sfeer/Komoot.tsx": () => import("../components/mockups/vandaag-sfeer/Komoot.tsx"),
  "./components/mockups/vandaag-sfeer/Strava.tsx": () => import("../components/mockups/vandaag-sfeer/Strava.tsx"),
  "./components/mockups/route-scherm/KomootKlassiek.tsx": () => import("../components/mockups/route-scherm/KomootKlassiek.tsx"),
  "./components/mockups/route-scherm/PlannerFirst.tsx": () => import("../components/mockups/route-scherm/PlannerFirst.tsx"),
  "./components/mockups/route-scherm/SparkiStijl.tsx": () => import("../components/mockups/route-scherm/SparkiStijl.tsx")
};
