// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sparki-reboot/Prototype.tsx": () => import("../components/mockups/sparki-reboot/Prototype.tsx"),
  "./components/mockups/vandaag-sfeer/Current.tsx": () => import("../components/mockups/vandaag-sfeer/Current.tsx"),
  "./components/mockups/vandaag-sfeer/Komoot.tsx": () => import("../components/mockups/vandaag-sfeer/Komoot.tsx"),
  "./components/mockups/vandaag-sfeer/Strava.tsx": () => import("../components/mockups/vandaag-sfeer/Strava.tsx")
};
